version: "3"
services:
  elasticsearch:
    image: elasticsearch:$ELASTIC_VERSION
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=$ELASTIC_SECURITY
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
    ports: 
    - "9200:9200"
    - "9300:9300"
    networks: ['elastic']
    
  kibana:
    image: kibana:$ELASTIC_VERSION
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
    ports:
    - "5601:5601"
    networks: ['elastic']
    links:
    - elasticsearch
    depends_on:
    - elasticsearch
    
  logstash:
    image: logstash:$ELASTIC_VERSION
    links:
    - elasticsearch
    volumes:
    - ./:/config-dir
    command: logstash -f /config-dir/logstash.conf
    depends_on:
    - elasticsearch
    networks: ['elastic']


networks:
  elastic: 
    driver: bridge